### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by hjkl950217** [dotnetcore/HttpReports#100]
## 问题
新建空项目，按[文档](https://www.yuque.com/httpreports/docs/eqyzq7) 进行配置`HttpReports.Dashboard`. 报错：
```
      Application startup exception
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'flushThreshold')
   at HttpReports.DeferFlushCollection`1..ctor(Int32 flushThreshold, Int32 flushSecond)
   at HttpReports.AsyncCallbackDeferFlushCollection`1..ctor(Func`3 callback, Int32 flushThreshold, Int32 flushSecond)
   at HttpReports.Storage.Abstractions.BaseStorage..ctor(BaseStorageOptions options)
   at HttpReports.Storage.MySql.MySqlStorage..ctor(IOptions`1 options, ILogger`1 logger)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.DependencyInjectionExtensions.UseHttpReportsDashboard(IApplicationBuilder app)
   at GMP.HttpReport.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in E:\test\GMP.HttpReport\Startup.cs:line 37
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
```

参考其它issue，都是配置问题。但是我检查过配置文件，是放在appsetting中的。

appsetting：
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",

  "HttpReportsDashboard": {
    "ExpireDay": 3,
    "Storage": {
      // "ConnectionString": "",
      "DeferSecond": 10,
      "DeferThreshold": 100
    },
    "Check": {
      "Mode": "Self",
      "Switch": true,
      "Endpoint": "",
      "Range": "500,2000"
    },
    "Mail": {
      "Server": "smtp.163.com",
      "Port": 465,
      "Account": "a@qq.com",
      "Password": "",
      "EnableSsL": true,
      "Switch": true
    }
  }
}
```

## 环境
windows10 2004 本机调试

**Comment by SpringLeee** [comment]
没有读取到配置信息哦，再检查一下把

**Comment by hjkl950217** [comment]
@SpringLeee 按官网文档直接赋值到appsetting.json的

**Comment by hjkl950217** [comment]
我在代码用action的那种方式配置启动起来了。。 放配置文件还是不行

**Comment by SpringLeee** [comment]
你把配置文件发出来我看下

**Comment by hjkl950217** [comment]
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*"

  "HttpReportsDashboard": {
    "ExpireDay": 3,
    "Storage": {
      // "ConnectionString": "",
      "DeferSecond": 10,
      "DeferThreshold": 100
    },
    "Check": {
      "Mode": "Self",
      "Switch": true,
      "Endpoint": "",
      "Range": "500,2000"
    },
    "Mail": {
      "Server": "smtp.163.com",
      "Port": 465,
      "Account": "a@qq.com",
      "Password": "",
      "EnableSsL": true,
      "Switch": true
    }
  }
}
```

**Comment by SpringLeee** [comment]
你是不是少了个点啊

**Comment by hjkl950217** [comment]
哦。。你是说  “"AllowedHosts": "*"”  这里么？ 这里没有。。我现在用的是action那种方式。。 appsetting.json里注释了。。我这里是放开注释发上来的。  提问的时候是没有少逗号的

**Comment by hjkl950217** [comment]
配置还好， 实在不行用代码里配置也可以。。  监控页面中请求内容和响应内容没有数据这种情况， 可能是什么问题呀？

**Comment by SpringLeee** [comment]
只有json格式的才会有请求内容和响应内容

**Comment by hjkl950217** [comment]
是请求里面必须是json格式么？ 如果请求` "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",`   ,返回时 返回的是`"Content-Type": "application/json"` 可以么

**Comment by SpringLeee** [comment]
那样应该只会有 响应内容才会被记录，你可以试试看

**Comment by hjkl950217** [comment]
额。。就是想通过加这个查看http请求的信息。。     而且页面上看到，似乎并没有“响应头”？
