### ISSUE TITLE
在应用程序已开始从请求正文中读取后，无法修改最大请求正文大小。

### ISSUE THREAD

**Issue by luoyao929** [dotnetcore/HttpReports#112]
下面的错误跟这个值【 MaxBytes 】有关系吗？我这边的项目安装HttpReports运行就会报这个错，卸载掉就正常了。

===============Error Log================
An unhandled exception has occurred while executing the request. (Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware)
System.InvalidOperationException: The maximum request body size cannot be modified after the app has already started reading from the request body.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Microsoft.AspNetCore.Http.Features.IHttpMaxRequestBodySizeFeature.set_MaxRequestBodySize(Nullable`1 value)
   at WalkingTec.Mvvm.Mvc.WtmMiddleware.InvokeAsync(HttpContext context, IOptionsMonitor`1 configs)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
[15:25:05.674 Information] CORS policy execution failed. (Microsoft.AspNetCore.Cors.Infrastructure.CorsService)
[15:25:05.675 Information] Request origin "http://localhost:8081" does not have permission to access the resource. (Microsoft.AspNetCore.Cors.Infrastructure.CorsService)
[15:25:05.678 Error] An exception was thrown attempting to execute the error handler. (Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware)
System.InvalidOperationException: The maximum request body size cannot be modified after the app has already started reading from the request body.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Microsoft.AspNetCore.Http.Features.IHttpMaxRequestBodySizeFeature.set_MaxRequestBodySize(Nullable`1 value)
   at WalkingTec.Mvvm.Mvc.WtmMiddleware.InvokeAsync(HttpContext context, IOptionsMonitor`1 configs)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
[15:25:05.687 Error] Connection id ""0HMAG0PUITEKN"", Request id ""0HMAG0PUITEKN:00000003"": An unhandled exception was thrown by the application. (Microsoft.AspNetCore.Server.Kestrel)
System.InvalidOperationException: The maximum request body size cannot be modified after the app has already started reading from the request body.
   at HttpReports.DefaultHttpReportsMiddleware.InvokeHttpCommonAsync(HttpContext context)
   at HttpReports.DefaultHttpReportsMiddleware.InvokeHttpAsync(HttpContext context)
   at HttpReports.DefaultHttpReportsMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by SpringLeee** [comment]
MaxBytes  没有关系，可以贴一下你的代码，方便我定位问题

**Comment by luoyao929** [comment]
<img width="836" alt="image" src="https://user-images.githubusercontent.com/17495689/127520842-dcfa5f77-fb20-4b2f-a198-a572e6964b90.png">
具体原因我没查到，我把UseHttpReports()从最上面移到现在的位置就没问题了。可能是跟我用的框架(WTM)产生 冲突了。谢谢哈
