### ISSUE TITLE
请求数据保存失败

### ISSUE THREAD

**Issue by messcf** [dotnetcore/HttpReports#21]
fail: HttpReports.Storage.MySql.MySqlStorage[0]
      Method: AddRequestInfoAsync Message: 请求数据保存失败
MySql.Data.MySqlClient.MySqlException (0x80004005): Data too long for column 'Route' at row 1
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 678
   at HttpReports.Storage.MySql.MySqlStorage.<>c__DisplayClass14_0.<<AddRequestInfoAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at HttpReports.Storage.MySql.MySqlStorage.LoggingSqlOperation(Func`2 func, String message, String method)

**Comment by SpringLeee** [comment]
看起来是 mysql 的 Route 字段长度不够了，当时给的50，我晚点更新下吧

**Comment by messcf** [comment]
麻烦您了  谢谢

**Comment by SpringLeee** [comment]
@messcf  请求报错地址，能发出来，路由为啥这么长。。

**Comment by messcf** [comment]
http://192.168.1.201:2000/paysystemfinance/Limit/GetChannelBusinessLimitListResultAsync 请求接口地址 路由

**Comment by SpringLeee** [comment]
@messcf  那没问题了，就是之前给的字段短了

**Comment by messcf** [comment]
Dashborad 里的 HttpReports  怎么替换成其他的名称

**Comment by SpringLeee** [comment]
@messcf  目前是不支持修改的
