### ISSUE TITLE
项目中包含CAP仪表盘的时候会产生无法访问流

### ISSUE THREAD

**Issue by jianxuanbing** [dotnetcore/HttpReports#28]
CAP版本：`2.6.0`
```
System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.MemoryStream.Seek(Int64 offset, SeekOrigin loc)
   at HttpReports.DefaultHttpReportsMiddleware.GetResponseBodyAsync(HttpContext context)
   at HttpReports.DefaultHttpReportsMiddleware.InvokeHttpAsync(HttpContext context)
   at HttpReports.DefaultHttpReportsMiddleware.InvokeAsync(HttpContext context)
   at DotNetCore.CAP.DashboardMiddleware.Invoke(HttpContext context) in C:\projects\cap\src\DotNetCore.CAP\Dashboard\CAP.DashboardMiddleware.cs:line 35
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by SpringLeee** [comment]
@jianxuanbing  好的，这个问题，我晚点跟一下

**Comment by SpringLeee** [comment]
@jianxuanbing  我本地调试，CAP 2.6.0 ，Dashboard 没有问题，收发消息也没问题，能具体说明什么情况下会报这个错吗

**Comment by jianxuanbing** [comment]
我尝试了下在CAP源码那边调试，没问题，是不是因为我自己增加的中间件来捕获请求后，导致流没有重新获取的原因导致呢？
另外，在跟CAP项目运行的时候，仪表盘路径好像无法打开`host:port/dashboar`，能否支持自定义路由呢

**Comment by jianxuanbing** [comment]
![image](https://user-images.githubusercontent.com/7100363/80441920-7c068080-893e-11ea-908d-921a2ba338c2.png)

![image](https://user-images.githubusercontent.com/7100363/80441955-8c1e6000-893e-11ea-86cc-4804f06bfada.png)

**Comment by SpringLeee** [comment]
@jianxuanbing 
- 流的问题已经修复了，还没发发上去
- 不建议 HttpReports 和Dashboard 一起用，建议Dashboard单独一个项目，因为HttpReports 会记录Dashboard 的请求
- UseHome = true/false，host:port 和 host:port/Dashboard这样，目前不支持自定义

**Comment by jianxuanbing** [comment]
能否增加忽略过滤地址的功能呢

**Comment by SpringLeee** [comment]
@jianxuanbing  最近要做的有这个功能的
