### ISSUE TITLE
提个小建议

### ISSUE THREAD

**Issue by NPUlrk** [dotnetcore/HttpReports#5]
首先赞一下，Web DashBoard的UI不错，集成、使用也很方便。就是我们有很多小的WebAPI项目，如果都要做监控就要部署很多套DashBoard，地址也不一样。建议项目集成时可以指定数据库表名或者按照系统名加前缀，HttpReports.Dashboard只部署一套，配置好数据库连接后右上角可以下拉选系统。

**Comment by NPUlrk** [comment]
忽略上面的建议，是我没仔细看文档，原来在AddHttpReportsMiddleware时加节点名称就行。提另外一个问题，如果项目先创建了数据库中的表，再启动HttpReports.Dashboard会报

> 数据库初始化失败！错误信息:Table 'requestinfo' already exists

我用的MySql数据库

**Comment by SpringLeee** [comment]
是的，支持多个项目，只需要分别引用Nuget 包，然后传入 不同的节点名称就好 
services.AddHttpReportsMiddleware(WebType.MVC, DBType.SqlServer,"Mall");
services.AddHttpReportsMiddleware(WebType.MVC, DBType.SqlServer,"Pay");

**Comment by SpringLeee** [comment]
你是手动创建表的吗，我没见到过这个bug

**Comment by NPUlrk** [comment]
> 你是手动创建表的吗，我没见到过这个bug

不是手动建表，你可以创建MySQL的空Scheme，然后先在项目里面启动，HttpReports会自动创建表，数据库里面可以看到，如果这时候再用控制台启动HttpReports.Dashboard就会报那个已存在表的问题，启动顺序反过来不会报错

**Comment by NPUlrk** [comment]
另外，我又发现一个问题，我在一个新项目里面引用了这个包启动没有问题，在之前的一个项目里面引用启动的时候就会报

> ...using method 'mysql_native_password' failed with message: Access denied for user...HttpReports.DefaultHttpReports.Init(IConfiguration config)

的错误，两个项目数据库连接字符串完全一样，也在同一台电脑上运行。两个项目最大的区别就是第二个报错的有使用EF Core，我在EF Core里也有连接这个数据库，只是Scheme不一样，但是EF Core的那些DbContex初始化不会报错，即使我换成同一个Scheme还是会在HttpReports初始化时报错。已经排除权限、网络等问题。网上搜了下有说跟MySQL版本有关的，我看了下EF引用的MySQL版本跟HttpReports都是8.0.18

**Comment by NPUlrk** [comment]
我这边下载的zip解压的那个HttpReports.Dashboard，第二次启动也会报表已经存在，建议加个判断，表存在就不用继续创建了
> 
Unhandled Exception: System.Exception: 数据库初始化失败！错误信息:Table 'requestinfo' already exists
   at HttpReports.Web.DataContext.DBFactory.InitDB() in G:\Lee\HttpReportsWeb\HttpReports.Web\DataContext\DBFactory.cs:line 50
   at HttpReports.Web.Startup.InitWebService(IServiceCollection services) in G:\Lee\HttpReportsWeb\HttpReports.Web\Startup.cs:line 87
   at HttpReports.Web.Startup.ConfigureServices(IServiceCollection services) in G:\Lee\HttpReportsWeb\HttpReports.Web\Startup.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at HttpReports.Web.Program.Main(String[] args) in G:\Lee\HttpReportsWeb\HttpReports.Web\Program.cs:line 17

**Comment by SpringLeee** [comment]
我这里是加了判断的， 我怀疑 可能是MySql 大小写的问题
 Select count(1) from information_schema.tables where table_name ='RequestInfo' and table_schema = 'HttpReports';

你可以尝试执行这句话 试试，看看能不能查询到 已经创建的表

**Comment by NPUlrk** [comment]
重复创建的问题我知道了，是判断表是否存在时指定了schema名称为HttpReports，我的Scheme名称又不是这个，建议取消这个条件（连接字符串中已经指定了要连接的Scheme）或者实现Scheme名称可配置

**Comment by SpringLeee** [comment]
你的意思是 你没有用HttpReports 的这个库是吧，你命名为其他名字了，这个地方暂时 是固定为HttpReports，ToDoList 近期会修改这个问题的
